import { Dimensions, StyleSheet } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

// 共通で使用する色をここへ集約
export const COLORS = {
  base: '#0A0A0A',
  surface: '#1A1A1A',
  accent: '#D4AF37',
  textPrimary: '#FFFFFF',
  textSecondary: '#8E8E93',
  border: '#2C2C2E',
  danger: '#EF4444',
  actionBlue: '#38BDF8',
  success: '#22C55E',
};

export const styles = StyleSheet.create({
  modalContainer: { flex: 1, backgroundColor: COLORS.base },
  modalHeader: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    padding: 15, 
    borderBottomWidth: 1, 
    borderBottomColor: COLORS.border, 
    alignItems: 'center' 
  },
  headerSideButton: { width: 70 },
  swipeIndicator: { width: 40, height: 4, backgroundColor: COLORS.border, borderRadius: 2, marginBottom: 5 },
  modalTitle: { fontSize: 15, fontWeight: 'bold', color: COLORS.accent },
  closeButtonText: { color: COLORS.textSecondary, fontSize: 13 },
  editButtonText: { color: COLORS.accent, fontSize: 13, fontWeight: 'bold' },
  saveButton: { backgroundColor: COLORS.accent, padding: 6, borderRadius: 15 },
  saveButtonText: { color: '#000', fontWeight: 'bold', fontSize: 11, textAlign:'center' },
  modalScroll: { flex: 1, padding: 15 },
  profileHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  profileTextContainer: { flex: 1, marginRight: 10 },
  genjiName: { fontSize: 24, fontWeight: '900', color: '#FFF' },
  realName: { fontSize: 12, color: COLORS.textSecondary },
  statusBadge: { marginTop: 5, padding: 4, paddingHorizontal: 10, borderRadius: 5, backgroundColor: COLORS.surface, alignSelf: 'flex-start' },
  statusBadgeText: { fontSize: 10, color: COLORS.accent, fontWeight: 'bold' },
  photoFrame: { width: 90, height: 110, borderRadius: 10, overflow: 'hidden', backgroundColor: COLORS.surface },
  photo: { width: '100%', height: '100%' },
  cameraButton: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  cameraText: { fontSize: 8, color: COLORS.textSecondary },
  sectionHeader: { marginTop: 25, marginBottom: 10 },
  sectionHeaderText: { color: COLORS.accent, fontSize: 12, fontWeight: 'bold' },
  sectionHeaderLine: { height: 1, backgroundColor: COLORS.border, marginTop: 5 },
  actionRowContainer: { flexDirection: 'row', alignItems: 'center' },
  sideActionGroup: { flexDirection: 'row' },
  sideActionButton: { marginLeft: 10, padding: 8, backgroundColor: COLORS.surface, borderRadius: 8 },
  fabWrapper: { position: 'absolute', bottom: 30, right: 20, alignItems: 'flex-end' },
  fabMenu: { backgroundColor: COLORS.surface, borderRadius: 20, padding: 10, marginBottom: 15, width: 200, borderWidth: 1, borderColor: COLORS.border },
  fabMenuItem: { flexDirection: 'row', padding: 12, borderBottomWidth: 1, borderBottomColor: '#222', alignItems: 'center' },
  fabMenuText: { color: '#FFF', marginLeft: 10, fontSize: 13, fontWeight: 'bold' },
  fabMainButton: { flexDirection: 'row', backgroundColor: COLORS.accent, padding: 12, paddingHorizontal: 20, borderRadius: 30, alignItems: 'center' },
  fabMainText: { color: '#000', fontWeight: 'bold', marginLeft: 8 },

  // --- デジタル履歴書 ---
  appPreviewBackdrop: { flex: 1, backgroundColor: '#0B1120' }, 
  appPreviewHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 10 },
  appHeaderTitle: { color: COLORS.accent, fontSize: 14, fontWeight: 'bold', letterSpacing: 1 },
  appProfileTop: { alignItems: 'center', marginTop: 10, marginBottom: 30 },
  appPhotoRing: { width: 140, height: 140, borderRadius: 70, borderWidth: 3, borderColor: '#8B5CF6', overflow: 'hidden', marginBottom: 15, justifyContent:'center', alignItems:'center' },
  appPhoto: { width: '100%', height: '100%' },
  appSubName: { color: '#94A3B8', fontSize: 13, marginBottom: 5 },
  appNameRow: { flexDirection: 'row', alignItems: 'center' },
  appMainName: { fontSize: 30, fontWeight: 'bold', color: '#FFF', marginRight: 10 },
  appStatusBadge: { backgroundColor: '#10B981', paddingVertical: 4, paddingHorizontal: 12, borderRadius: 12 },
  appStatusText: { color: '#FFF', fontSize: 11, fontWeight: 'bold' },

  appDashRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  appBasicCard: { flex: 1, backgroundColor: '#3B0764', borderRadius: 16, padding: 15, marginRight: 10 },
  appContactCard: { flex: 1, backgroundColor: '#171717', borderRadius: 16, padding: 15, borderWidth: 1, borderColor: '#D4AF37' },
  appCardTitle: { color: '#E9D5FF', fontSize: 12, fontWeight: 'bold', marginBottom: 15 },
  appCardTitleGold: { color: '#D4AF37', fontSize: 12, fontWeight: 'bold', marginBottom: 15 },
  appBasicIcons: { flexDirection: 'row', justifyContent: 'space-between' },
  appIconStat: { alignItems: 'center' },
  appIconEmoji: { fontSize: 18, marginBottom: 5 },
  appIconText: { color: '#FFF', fontSize: 13, fontWeight: 'bold' },
  appContactIcons: { flexDirection: 'row', justifyContent: 'space-between' },
  appContactBtn: { alignItems: 'center' },
  appContactLabel: { color: '#94A3B8', fontSize: 10, marginTop: 5 },

  appSectionLabel: { color: '#94A3B8', fontSize: 12, fontWeight: 'bold', letterSpacing: 1, marginBottom: 15, paddingLeft: 5 },
  categoryGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  categoryCard: { width: '48%', backgroundColor: '#1E293B', borderRadius: 20, padding: 20, marginBottom: 15, alignItems: 'center', borderWidth: 1, borderColor: '#334155' },
  categoryIconBg: { width: 50, height: 50, borderRadius: 25, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
  categoryTitle: { color: '#FFFFFF', fontSize: 15, fontWeight: 'bold', marginBottom: 4 },
  categorySub: { color: '#94A3B8', fontSize: 11 },

  // --- タイル状ポップアップ ---
  detailPopupOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.85)', justifyContent: 'center', alignItems: 'center' },
  detailPopupCard: { width: '92%', maxHeight: '82%', backgroundColor: '#1E293B', borderRadius: 20, padding: 20, borderWidth: 1, borderColor: COLORS.accent },
  detailPopupHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20, paddingBottom: 10, borderBottomWidth: 1, borderBottomColor: '#334155' },
  detailPopupTitle: { color: COLORS.accent, fontSize: 18, fontWeight: 'bold' },
  detailPopupContent: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  detailPopupRow: { backgroundColor: '#0F172A', padding: 12, borderRadius: 10, marginBottom: 10 },
  detailPopupRowHalf: { width: '48%' },
  detailPopupRowFull: { width: '100%' },
  detailPopupLabel: { color: '#94A3B8', fontSize: 10, fontWeight: 'bold', marginBottom: 4 },
  detailPopupValue: { color: '#FFF', fontSize: 14, fontWeight: 'bold' },
  noDataText: { color: '#94A3B8', textAlign: 'center', width: '100%', marginTop: 20, fontSize: 14 },
  idSectionContainer: {
    marginBottom: 20,
    paddingHorizontal: 15,
  },
  idCardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  idCardBox: {
    width: '48%',
    height: 110,
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2C2C2E',
    overflow: 'hidden',
  },
  idCardImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  idCardPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderStyle: 'dashed',
    borderWidth: 1.5,
    borderColor: 'rgba(212, 175, 55, 0.4)',
    borderRadius: 12,
    backgroundColor: 'rgba(26,26,26,0.6)',
    margin: 2,
  },
  idCardText: {
    color: '#D4AF37',
    fontSize: 12,
    fontWeight: 'bold',
    marginTop: 8,
  },
  
});